import classNames from 'util/classNames';

import { useEffect, useState } from 'react';

import API from 'app/api/API';
import ItemArea from 'components/ItemArea/ItemArea';
import { Row, Col } from 'react-bootstrap';

import styles from '../styles/Home.module.scss';

export default function Home() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    API.get('/shop/products').then((res) => {
      setProducts(res);
      console.log(res);
    });
  }, []);
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={classNames(styles.body, 'container')}>
        <h5>SİZİN İÇİN SEÇTİKLERİMİZ</h5>
        <Row>
          {products.map((product) => (
            <Col key={product._id} xs={6} md={4} lg={2}>
              <ItemArea item={product} />
            </Col>
          ))}
        </Row>
      </div>
    </div>
  );
}
